default: &defaults
  facebook_app_id    : ''
  facebook_app_secret: ''
  promoters          : [9,10]
  detractors         : [0,1,2,3,4,5,6]
  passives           : [7,8]
  liked              : 1
  disliked           : -1
  neutral            : 0

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
